### ISSUE TITLE
Add support for cli options? 

### ISSUE THREAD

**Issue by boyney123** [serverless-components/website#11]
Hey,

I'm playing around this component, and it seems to be working great 👍 .

One thing I cannot get my head around is different environments if I hook this up to some kind of CI process.

For example, if I wanted to support `dev`, `staging`, and `production`

How would you go about doing this?

My thought was to change the bucket name that the code gets pushed too, but it looks like I cannot do this with `cli options` like I could in the standard `serverless.yml` setup?

**Comment by eahefnawy** [comment]
Thanks for opening this up. We currently don't support cli options because components could also work programmatically without a CLI.

More info regarding CLI and staging was already discussed in this issue:
https://github.com/serverless/components/issues/481

**Comment by boyney123** [comment]
Heey @eahefnawy, thanks for the quick response.

Thanks for the link into the other issue, I will check that out and see what's going on!

Great work keep it up!
