### ISSUE TITLE
Duplicate plugin/preset detected.

### ISSUE THREAD

**Issue by davegariepy** [serverless-components/website#49]
After installing and trying to run  `npm run build` I got the error: 
`Duplicate plugin/preset detected.` 

I was able to resolve this by removing the `plugins` section from `package.json`

since the preset `nano-react-app` already includes those plugins, they don't need to be declared again in `package.json` heres a related stackoverflow [explaining](https://stackoverflow.com/questions/52798987/babel-7-fails-with-single-plugin-saying-duplicate-plugin-preset-detected)

**Comment by fuschini** [comment]
@davegariepy just had the same problem and your fix made it work!

**Comment by eahefnawy** [comment]
Thanks all. We just fixed this issue in the template.
