### ISSUE TITLE
Folders are not uploaded/created on S3 correctly.

### ISSUE THREAD

**Issue by fodurrr** [serverless-components/website#7]
The folders are not uploaded/not created on S3. The folder names are merged into the filenames as string (flattened), therefore static assets are not displayed on the created website, worst case with create-react-app that application will not even start because static chunk JavaScript files are created in the static folder.

![image](https://user-images.githubusercontent.com/10008597/65653307-a8ef5f80-e00c-11e9-98be-8e07832ccc37.png)

When I upload the **static folder** via the AWS console manually into the same bucket then everything works fine.

Probably the problem is here: [websiteBucket.upload](https://github.com/serverless-components/website/blob/master/serverless.js#L100).

Btw where can i find this [@serverless/aws-s3](https://www.npmjs.com/package/@serverless/aws-s3) package which has the `websiteBucket.upload` function on github? May be I could do a PR.
Thanks

**Comment by eahefnawy** [comment]
@fodurrr are you using windows? does this PR fix the issue?
https://github.com/serverless-components/aws-s3/pull/4

**Comment by fodurrr** [comment]
Yes I am on windows. 
My problem is not fixed yet but it is probably because **website components** has in the package.json ` old version of "@serverless/aws-s3": "^2.0.0"` so may be it should be updated?

**Comment by eahefnawy** [comment]
Thanks @fodurrr ... Merged and released
